# Generated by Django 6.1.1 on 2026-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='', max_length=10, verbose_name='Рівень'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='target_position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Посада'),
        ),
    ]
