# Generated by Django 6.1.1 on 2026-09-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Питання')),
                ('ai_answer', models.TextField(blank=True, null=True, verbose_name='Відповідь від АІ')),
                ('user_answer', models.TextField(blank=True, null=True, verbose_name='Редагована відповідь')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядковий номер питання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_sessions.session', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
                'ordering': ['order'],
            },
        ),
    ]
