# Generated by Django 6.1.1 on 2026-10-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0002_session_error_message'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_question_order_in_session'),
        ),
    ]
