# Generated by Django 6.1.1 on 2026-09-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10, verbose_name='Формат')),
                ('status', models.CharField(choices=[('pending', 'В очікуванні експорту'), ('processing', 'В процесі'), ('ready', 'Готово'), ('failed', 'Невдало')], default='pending', max_length=25, verbose_name='Статус')),
                ('file', models.FileField(blank=True, upload_to='exports/%Y/%m/%d/', verbose_name='Файл')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID фонової задачі')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='Відбиток вмісту')),
                ('error_message', models.TextField(blank=True, verbose_name='Пояснення помилки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено експорт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Генерація завершилась')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='interview_sessions.session', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'Експорт',
                'verbose_name_plural': 'Експорти',
                'ordering': ['-created_at'],
            },
        ),
    ]
