# Generated by Django 6.1.1 on 2026-09-19 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва задачі')),
                ('description', models.TextField(verbose_name='Умова задачі')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, verbose_name='Складність')),
                ('language', models.CharField(max_length=50, verbose_name='Мова програмування')),
                ('skeleton', models.TextField(verbose_name='Шаблон коду')),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='Список об’єктів із input та expected_output; формат визначає перевіряльник.', verbose_name='Перевірочні приклади')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Задача з програмування',
                'verbose_name_plural': 'Задачі з програмування',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_solution', models.TextField(blank=True, verbose_name='Код користувача')),
                ('status', models.CharField(choices=[('not_started', 'Ще не виконане'), ('failed', 'Провалено'), ('partial', 'Частково правильно виконано'), ('success', 'Успішно')], default='not_started', max_length=30, verbose_name='Статус')),
                ('feedback', models.TextField(blank=True, verbose_name='Пояснення оцінки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.codingtask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Спроба розв’язання',
                'verbose_name_plural': 'Спроби розв’язання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва завдання')),
                ('description', models.TextField(verbose_name='Умова завдання')),
                ('difficulty', models.CharField(choices=[('easy', 'Легка'), ('medium', 'Середня'), ('hard', 'Складна')], default='easy', max_length=10, verbose_name='Складність')),
                ('status', models.CharField(choices=[('not_started', 'Ще не виконане'), ('failed', 'Провалено'), ('partial', 'Частково правильно виконано'), ('success', 'Успішно')], default='not_started', max_length=30, verbose_name='Статус')),
                ('user_solution', models.TextField(blank=True, verbose_name='Код користувача')),
                ('feedback', models.TextField(blank=True, verbose_name='Пояснення оцінки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='questions.question', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Практика до питання',
                'verbose_name_plural': 'Практики до питань',
                'ordering': ['-created_at'],
            },
        ),
    ]
