# Generated by Django 6.1.1 on 2026-10-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtask',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легка'), ('medium', 'Середня'), ('hard', 'Складна')], max_length=10, verbose_name='Складність'),
        ),
    ]
