# Generated by Django 6.1.1 on 2026-09-13 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва сесії')),
                ('status', models.CharField(choices=[('created', 'Сесія створена'), ('processing', 'Обробка'), ('ready', 'Готово'), ('failed', 'Помилка')], default='created', max_length=20, verbose_name='Статус')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Сесія',
                'verbose_name_plural': 'Сесії',
                'ordering': ['-created_at'],
            },
        ),
    ]
